/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=WorkerBindings worker/bindings.d.ts` (hash: 024cc53840c29304fb65dec42a235226)
interface __BaseEnv_WorkerBindings {
	DB?: D1Database;
	ASSETS: Fetcher;
	CF_ACCESS_TEAM?: string;
	CF_ACCESS_AUD?: string;
	CONNECT_DEPLOYMENT_ID?: string;
	DASHBOARD_SERVICE_TOKEN?: string;
	CONNECT_MANAGERS?: string;
	CONNECT_TOKEN_KEYS?: string;
	CF_ACCESS_DEV_BYPASS?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		CF_ACCESS_TEAM: string;
		CF_ACCESS_AUD: string;
		CONNECT_DEPLOYMENT_ID: string;
		DASHBOARD_SERVICE_TOKEN: string;
		CONNECT_MANAGERS: string;
		CONNECT_TOKEN_KEYS: string;
	}
	interface DevEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		CF_ACCESS_TEAM: string;
		CF_ACCESS_AUD: string;
		CF_ACCESS_DEV_BYPASS: string;
		DASHBOARD_SERVICE_TOKEN: string;
		CONNECT_DEPLOYMENT_ID: string;
		CONNECT_MANAGERS: string;
		CONNECT_TOKEN_KEYS: string;
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCESS_TEAM" | "CF_ACCESS_AUD" | "CONNECT_DEPLOYMENT_ID" | "DASHBOARD_SERVICE_TOKEN" | "CONNECT_MANAGERS" | "CONNECT_TOKEN_KEYS" | "CF_ACCESS_DEV_BYPASS">> {}
}
